### PR TITLE
Preserve unsubscribe_after limit across reconnects

### LINKED ISSUE #1302: `unsubscribe_after` forgotten on reconnection
### Observed behavior

In the following sequence:

1. subscribe
2. `unsubscribe_after` n
3. reconnect
4. reach `n` messages
5. additional messages published on topic

...in step 3, `async-nats` re-subscribes on the new connection without re-sending an `UNSUB {sid} {max}` (where max = prev_max - delivered). 

...and in step 4, `async-nats` appears to remove the subscription info from `ConnectionHandler::subscriptions` [here](https://github.com/nats-io/nats.rs/blob/053944d541e1d0ad021a442d0d33f07276642cca/async-nats/src/lib.rs#L691) but not actually send an `UNSUB` message either.

...so in step 5, it still continues receiving messages on the sid from the server for this topic, even though they go nowhere. This is a waste in bandwidth that could add up in some use cases.

### Expected behavior

In step 2, I think it should send the `UNSUB {sid} {max}` immediately to avoid this.

### Server and client version

Rust async nats client, current head (053944d541e1d0ad021a442d0d33f07276642cca)

### Host environment

any

### Steps to reproduce

I hacked the `force_reconnect` test to observe this:

* call `unsub_after` pre-reconnect
* exceed this limit post-reconnect
* just to ensure the test doesn't quit before the spurious messages are received, make a new subscription on a different topic, publish something on it, and wait for it to go through.
* add an `else if` branch [here](https://github.com/nats-io/nats.rs/blob/053944d541e1d0ad021a442d0d33f07276642cca/async-nats/src/lib.rs#L728) to actually see the spurious messages

I'd be happy to put together a fix. The debatable point is how to automatically test the fix is correct. I believe it's normal to get messages on unknown sids for a bit after enqueuing an `UNSUB` because there's a delay before the server actually handles it, and it could have enqueued another message on the topic in the meantime. So this isn't worth causing an error over in general, or likely even enqueueing something on `events_tx`. But we can arrange the sequencing in a test so these messages shouldn't happen if the client is behaving properly. Maybe are there connection stats somewhere we can add a counter to for this, and the test can check those after the fact? I'm open to ideas.

### PR DESCRIPTION
**Pull request by MattPatchava**
Fixes #1302 

## Problem
After a reconnect, `ConnectionHandler::handle_reconnect` resends `SUB` for each active subscription but not `UNSUB {sid} {max}` for subscriptions with an `unsubscribe_after` limit. The server would continue to deliver messages beyond the limit, wasting bandwidth and CPU even though the client silently discards them.

## Fix
After resubscribing on reconnect, immediately enqueue an `UNSUB {sid} {remaining}` where `remaining` is `max - delivered`. Both frames are flushed together so they arrive at the server atomically, minimizing the window for extra messages to be delivered.

## Test
A TCP proxy is bound between the client and server to observe server side behavior. The proxy counts `MSG test` frames (for `test` subscription) and asserts that none arrive after the `unsubscribe_after` limit after a `force_reconnect`. This is necessary because the client already silences messages past the limit locally, so a proxy was needed to prove that the server actually stopped sending messages for this subscription.

### CODE REVIEW

File: async-nats/src/lib.rs [hunk 1]
```diff
@@ -977,6 +977,13 @@ impl ConnectionHandler {
                 subject: subscription.subject.to_owned(),
                 queue_group: subscription.queue_group.to_owned(),
             });
+
+            if let Some(max) = subscription.max {
+                self.connection.enqueue_write_op(&ClientOp::Unsubscribe {
+                    sid: *sid,
+                    max: Some(max - subscription.delivered),
```
Comment (Jarema) [inline async-nats/src/lib.rs]: we should protect against `delivered > max` with `saturating_sub`.
Might sound bit defensive, but you never know what happens over the network and such guard is cheap.

**Review by Jarema — CHANGES_REQUESTED** [review]
Thanks for the PR!

One small correction.

File: async-nats/src/lib.rs (hunk 1 above)
Comment (MattPatchava) [reply async-nats/src/lib.rs]: @Jarema done, updated to `saturating_sub`

**Comment by MattPatchava** [comment]
Hey @Jarema, looks like the branch has picked up the server pool work that's already on main, probably from an accidental force push. Needs a rebase onto main to clean it up before this can merge

**Review by Jarema — APPROVED** [review]
LGTM!
