### PR TITLE
Fix stack overflow in object store

### LINKED ISSUE #730: Stack overflow when using `ObjectStore::put`
### Cause and effect

Having a call to `ObjectStore::put` anywhere in the application may cause a stack overflow to occur on application startup. This is caused by the internal buffer being allocated on the stack.

```rust
const DEFAULT_CHUNK_SIZE: usize = 128 * 1024;
// ...
let mut buffer = [0; DEFAULT_CHUNK_SIZE];
```

### Prior work

There was an attempt at fixing this issue in #722, but that PR has been scrapped. This issue exists to track an alternative solution.

---

**NATS version**: 0.22.1
**Rust compiler version**: 1.65.0
**Operating system**: Windows 11

### PR DESCRIPTION
**Pull request by Jarema**
Fixes #730 

Signed-off-by: Tomasz Pietrek <tomasz@nats.io>

### CODE REVIEW

File: async-nats/src/jetstream/object_store/mod.rs [hunk 1]
```diff
@@ -259,11 +259,11 @@ impl ObjectStore {
         let mut object_chunks = 0;
         let mut object_size = 0;
 
-        let mut buffer = [0; DEFAULT_CHUNK_SIZE];
+        let mut buffer = Box::new([0; DEFAULT_CHUNK_SIZE]);
```
Comment (caspervonb) [inline async-nats/src/jetstream/object_store/mod.rs:262]: Just do a vec?

Comment (Jarema) [reply async-nats/src/jetstream/object_store/mod.rs:262]: few bytes saved on not having `len` field? 😄

**Review by caspervonb — APPROVED** [review]
lgtm
